config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  resources :blogs
  root 'posts#index'
  get '/posts' => 'posts#index'
  get '/posts/new' => 'posts#new'
  post '/posts'=> 'posts#create'
  get '/posts/:id' => 'posts#show'
  get '/posts/:id/edit' => 'posts#edit'
  put '/posts/:id' => 'posts#update'
  delete '/posts/:id' => 'posts#destroy'

  get '/users/index' => 'users#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  mount_uploader :postimage, PostImageUploader
  belongs_to :user
  # validates :postimage, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_action은 하나의 액션을 실행하기 전에 해당 메소드를 실행.
  # 컨트롤러.. filter
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  # only, except.. 없으면 모든 action
  before_action :authenticate_user!, except: :index
  # before_action :is_owner?, only: [:edit, :update, :destroy]
  load_and_authorize_resource except: :edit, param_method: :post_params



  def index
    # 모든 것을 보여주는 곳...
      @posts = Post.where("title LIKE ?", "%#{params["q"]}%")
  end

  # Create
  def new
  end

  def create
    current_user.posts.create(post_params)
    # current_user => User의 인스턴스
    # current_user.posts => Post의 인스턴스
    redirect_to '/'
  end

  # Read
  def show
    # @post = Post.find(params[:id])
    # authorize! :read, @post
  end

  # update
  def update
    # @post = Post.find(params[:id])
    # authorize! :update, @post
    @post.update(post_params)
    redirect_to "/posts/#{@post.id}"
  end

  def edit
    # authorize! :update, @post
    # @post = Post.find(params[:id])
  end

  # delete
  def destroy
    # authorize! :destroy, @post
    @post.destroy
    redirect_to '/'
    # @post = Post.find(params[:id])
  end

  # private 위에는 public이라서 url로 요청오면 그것을 받아서 뷰를 보여준다.
  private
  # private은 해당 컨트롤러(PostsController)에서만 사용가능함.
  # 객체에서 private 속성을 가지면.. 클래스 내부에서만 접근이 가능했었고,
  # 이외의 상속받은 클래스나 객체 인스턴스에서도 접근이 불가능했음.
  def set_post
    @post = Post.find(params[:id])
  end

# strong parameter
  def post_params
    params.require(:post).permit(:title, :content, :postimage)
      # "post"=>{"title"=>"asdf", "content"=>"q1111"}
  end

  def is_owner?
    # 게시글의 주인, 로그인한 사람이 같지 않으면
    redirect_to '/' and return unless @post.user_id == current_user.id
    # redirect_to '/'
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/delete.html.erb
<h1>Posts#delete</h1>
<p>Find me in app/views/posts/delete.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>
<%= form_tag("/posts/#{@post.id}", method: "put", multipart: true) do %>
  <%= text_field_tag("post[title]", @post.title) %>
  <%= text_area_tag("post[content]", @post.content) %>
  <%= file_field_tag("post[postimage]") %><br />
  <%= submit_tag %>
<% end %>

app/views/posts/index.html.erb
<div class="text-right">
  <%= link_to "새글쓰기", posts_new_path %>
</div>

<% @posts.in_groups_of(3, false).each do |group| %>
  <div class="row mt-3">
  <% group.each do |post| %>
    <div class="col-4">
      <a href="/posts/<%=post.id%>">
        <img src="<%=post.postimage.thumb%>" class="img-fluid">
      </a>
    </div>
  <% end %>
  </div>
<% end %>

app/views/posts/new.html.erb
<!-- <form action="/posts" method="post" enctype="multipart/form-data">
  <input type="text" name="title" /><br />
  <textarea name="content"></textarea><br />
  <input type="file" name="post[postimage]" /><br />
  <input type="hidden" name="authenticity_token" value="<%# form_authenticity_token%>">
  <input type="submit" />
</form> -->
<hr />
<div class="container">
<%= form_tag("/posts", method: "post", multipart: true) do %>
  <div class="form-group">
    <%= label_tag(:post_title, "제목")%>
    <%= text_field_tag "post[title]", "", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= label_tag(:post_content, "내용")%>
    <%= text_area_tag("post[content]", "", class: "form-control") %>
  </div>
  <div class="form-group">
    <%= label_tag(:post_postimage, "첨부파일")%>
    <%= file_field_tag("post[postimage]", class: "form-control") %><br />
  </div>
    <%= button_tag("제출", class: "btn btn-primary") %>
  </div>
<% end %>
</div>

app/views/posts/show.html.erb
<div class="d-flex justify-content-center mt-3">
  <figure class="figure">
    <img src="<%= @post.postimage%>" class="figure-img img-fluid rounded" style="height: 70vh;">
    <figcaption class="figure-caption">
      <h5><%= @post.title %></h5>
      <h6 class="text-right">글쓴이 : <%= @post.user.username %></h6>
      <h6><%= @post.content %></h6>
    </figcaption>
  </figure>
</div>




<%# if can? :update, @post %>
  <p><a href="/posts/<%=@post.id%>/edit">수정</a></p>
<%# end %>

<% if can? :destroy, @post %>
  <p><a href="/posts/<%=@post.id%>" data-method="delete" data-confirm="삭제할래?">삭제</a></p>
<% end %>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>